apiVersion: v1
data:
  create-ocp-namespace-swt-schema.json: "{\n  \"$id\": \"classpath:/schemas/create-ocp-namespace-swt-schema.json\",\n
    \ \"title\": \"Workflow input data\",\n  \"$schema\": \"http://json-schema.org/draft-07/schema#\",\n
    \ \"type\": \"object\",\n  \"properties\": {\n    \"namespace\": {\n      \"title\":
    \"Namespace Name\",\n      \"description\": \"OCP namespace to create\",\n      \"type\":
    \"string\",\n      \"pattern\": \"^[a-z0-9]([-a-z0-9]*[a-z0-9])?$\"\n    },\n
    \   \"git_host\": {\n      \"title\": \"GitLab Host\",\n      \"type\": \"string\",\n
    \     \"description\": \"The gitlab host to use, example: gitlab.acme.com\"\n
    \   },\n    \"requester\": {\n      \"title\": \"Requester\",\n      \"type\":
    \"string\",\n      \"description\": \"The requester of the namespace\",\n      \"pattern\":
    \"^[a-z0-9]([-a-z0-9]*[a-z0-9])?$\"\n    }, \n    \"size\": {\n      \"title\":
    \"Size\",\n      \"type\": \"string\",\n      \"description\": \"The size of the
    namespace (small, medium, large). A large namespace requires approval.\",\n      \"enum\":
    [\n        \"small\",\n        \"medium\",\n        \"large\"\n      ]\n    },\n
    \   \"reason\": {\n      \"title\": \"Reason\",\n      \"type\": \"string\",\n
    \     \"description\": \"The reason a large namespace is required\"\n    },    \n
    \   \"recipients\": {\n      \"title\": \"Recipients\",\n      \"type\": \"array\",\n
    \     \"description\": \"A list of recipients for the notification in the format
    of 'user:<namespace>/<username>' or 'group:<namespace>/<groupname>', i.e. 'user:default/jsmith'\",\n
    \     \"items\": {\n        \"title\": \"Recipient\",\n        \"type\": \"string\",\n
    \       \"pattern\": \"^(user|group):[a-z0-9]([-a-z0-9]*[a-z0-9])?/([a-z0-9]([-a-z0-9]*[a-z0-9])?)$\"\n
    \     },\n      \"minItems\": 1\n    }\n  },\n  \"required\": [\n    \"namespace\",\n
    \   \"requester\",\n    \"size\",\n    \"git_host\",\n    \"recipients\"\n  ]\n}"
  workflow-output-schema.json: |-
    {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "WorkflowResult",
        "description": "Schema of workflow output",
        "type": "object",
        "properties": {
            "result": {
                "type": "object",
                "properties": {
                    "completedWith": {
                        "description": "The state of workflow completion.",
                        "type": "string",
                        "enum": [
                            "error",
                            "success",
                            "warning"
                        ]
                    },
                    "message": {
                        "description": "High-level summary of the current status, free-form text, human readable.",
                        "type": "string"
                    },
                    "nextWorkflows": {
                        "description": "List of workflows suggested to run next. Items at lower indexes are of higher priority.",
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "description": "Workflow identifier",
                                    "type": "string"
                                },
                                "name": {
                                    "description": "Human readable title describing the workflow.",
                                    "type": "string"
                                }
                            },
                            "required": [
                                "id",
                                "name"
                            ]
                        }
                    },
                    "outputs": {
                        "description": "Additional structured output of workflow processing. This can contain identifiers of created resources, links to resources, logs or other output.",
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "key": {
                                    "description": "Unique identifier of the option. Preferably human-readable.",
                                    "type": "string"
                                },
                                "value": {
                                    "description": "Free form value of the option.",
                                    "anyOf": [
                                        {
                                            "type": "string"
                                        },
                                        {
                                            "type": "number"
                                        }
                                    ]
                                },
                                "format": {
                                    "description": "More detailed type of the 'value' property. Defaults to 'text'.",
                                    "enum": [
                                        "text",
                                        "number",
                                        "link"
                                    ]
                                }
                            },
                            "required": [
                                "key",
                                "value"
                            ]
                        }
                    }
                }
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: 01-create-ocp-namespace-swt-resources-schemas
